### ISSUE TITLE
Install/configure Fedora 3 export tool for arch environment

### ISSUE THREAD

**Issue by eporter23** [emory-libraries/dlp-selfdeposit#102]
See prior work and documentation here: https://github.com/emory-libraries/dlp-selfdeposit/blob/a22b52df6901f35bd4eb05c5ff94bf1c98e41518/lib/fedora/MIGRATE_FEDORA3_OBJECTS_TUTORIAL.md

**Comment by eporter23** [comment]
@bwatson78 Can you please refine this ticket as needed? I found this readme, but I am not sure what else needs to be added.

**Comment by bwatson78** [comment]
I will. I will meetup with @jcrompton42 when she has time to install the necessities.

**Comment by eporter23** [comment]
@bwatson78 and @jcrompton42 cc @rotated8  we may want to chat about this before opening a firewall, since there is data in Fedora 3 that shouldn't be public?

**Comment by jcrompton42** [comment]
This would still be a system entirely reachable only in vpn, if that helps.
________________________________
From: eporter23 ***@***.***>
Sent: Friday, March 8, 2024 3:07 PM
To: emory-libraries/dlp-selfdeposit ***@***.***>
Cc: Crompton, Beth ***@***.***>; Mention ***@***.***>
Subject: [External] Re: [emory-libraries/dlp-selfdeposit] Install/configure Fedora 3 export tool for arch environment (Issue #102)


@bwatson78<https://github.com/bwatson78> and @jcrompton42<https://github.com/jcrompton42> cc @rotated8<https://github.com/rotated8> we may want to chat about this before opening a firewall, since there is data in Fedora 3 that shouldn't be public?

**Comment by eporter23** [comment]
There is a ticket into OIT and Beth is handling questions about this.
