### ISSUE TITLE
Mimetype and filenames at the file-level (Fedora/S3)

### ISSUE THREAD

**Issue by eporter23** [emory-libraries/dlp-selfdeposit#175]
When navigating the S3 buckets, I am finding that a binary file is stored as something like /ocflpath/to/original.
When I download the file, it doesn't download with its actual filename and does not have a file extension or the original mime type associated. 
The Fedora record for the binary shows the filename, but no mime type, whereas the FileSet record does.
If I download a file through Fedora or through Hyrax, the file downloads with the actual filename and has a mime type.
If I browse the OCFL root, locate a binary file, download and try to open it, there is only a generic filename (e.g. "original") and there is no mime type associated with the file - anything I try to open is treated as a text file. 

See [this document](https://docs.google.com/document/d/1xIlHqBn5WKis7JRoV7hwGPvg0is9jK4pw5b72t46BO4/edit#heading=h.ba4m27kt1284) for more detailed notes and examples.

Example (ironically, I can't attach the actual file because Zenhub can't determine what kind of file it is!) via screenshot of a PNG file when opened after downloading directly from S3. The actual filename is IMG_5223.PNG, but when downloading from S3, it becomes a file called "original" which has application/octet-stream assigned.

<img width="1229" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBMEU3QkE9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--6077802fa8f57678a62f88fc31c4a61091e340de/Screenshot%202024-04-05%20at%2010.51.58%E2%80%AFAM.png" alt="Screenshot 2024-04-05 at 10.51.58 AM.png" />

**Comment by eporter23** [comment]
Update: I reviewed this question with the Fedora tech team on 4/11/24 and further information is needed to determine if this behavior is on the Fedora side or Hyrax side. We may want to do some more testing on our end and also reach out to Hyrax folks about this.

**Comment by eporter23** [comment]
See also FileMetadata objects and this Samvera property stored in Fedora: ```
/ns# fileIdentifier
fedora://10.65.89.199:8080/fcrepo/rest/production/1cfca99a-cce1-42b9-a02d-1f7d9419b376/original
```

**Comment by bwatson78** [comment]
Initial findings: Within the S3 example in the accompanying document, I was able to locate the filename in the version's `/.fcrepo/fcr-root.json`. It is true that the mime type also in this JSON document matches the same wrong filetype in all locations (UI as well as S3), but the true mime type can be pulled from the filename. If we worked the S3 buckets programmatically, we could save the file correctly.

**Comment by bwatson78** [comment]
After uploading a binary file to the the Fedora Depo Arch instance (found [here](https://fedora-depo-arch.libraries.emory.edu/fcrepo/rest/production/755beedf-09a2-45c6-9ff3-9f1211b88c9a/fcr:metadata)), I can confirm that the default behavior for any binary uploaded to a Fedora is to store the file itself as an octet stream with the filename being the SHA256 digestion of "info:fedora/production/<<id assigned by Hyrax/Fedora>>" or ""info:fedora/production/<<id assigned by Hyrax/Fedora>>/original". The UI takes the values stored when the file was originally uploaded from `content/.fcrepo/fcr-root.json` to reapply the filename back to the stored binary.

I can also confirm, after examining Valkyrie's Fedora storage adapter, that they also default the mime type to octet stream unless a mime type is explicitly passed to the uploading method (which Hyrax doesn't). 

It is possible to alter Valkyrie's uploading code to force the creation of n-triple fields that contain both the mime type as well as the filename, but if our main concern is to have the filename available so that we can extract the binaries with the original filename intact, we could easily do that by reading the JSON available to us in `content/.fcrepo/fcr-root.json`.

**Comment by bwatson78** [comment]
For reference, this is the ingested file I uploaded as a test in the above comment withing the S3 bucket:
https://us-east-1.console.aws.amazon.com/s3/buckets/fedora-depo-arch-binaries?prefix=790/3b3/442/7903b34426b98f48c05d3138128fb2672af29e1d2cbd9c3c7567981a1ff8aebd/&region=us-east-1&bucketType=general

**Comment by eporter23** [comment]
Contents of fcr-root.json for a Hyrax-Valkyrie managed upload - note that the filename is retained even if the mime type is not. 
``` 
{
    "id": "info:fedora/production/3b897eee-5667-41fb-9750-49eae82936c9/original",
    "parent": "info:fedora/production/3b897eee-5667-41fb-9750-49eae82936c9",
    "stateToken": "2E742C3250CB602DFC1B3CE783760994",
    "interactionModel": "http://www.w3.org/ns/ldp#NonRDFSource",
    "mimeType": "application/octet-stream",
    "filename": "IMG_5223.PNG",
    "contentSize": 3607020,
    "digests": ["urn:sha-512:6353c03cb148e718a4097549ca96486de2d15d4c21c02de96d21e166aced32a0543bbba902100d858e15051c644bf88a1e4f5cec5568ecbe926ee1666aa9dcdd"],
    "createdDate": "2024-03-25T16:55:40.194001Z",
    "lastModifiedDate": "2024-03-25T16:55:40.194001Z",
    "mementoCreatedDate": "2024-03-25T16:55:40.338675Z",
    "archivalGroup": false,
    "objectRoot": true,
    "deleted": false,
    "contentPath": "original",
    "headersVersion": "1.0"
}```
