### ISSUE TITLE
Spike: determine if RIIIF is functional in our setup

### ISSUE THREAD

**Issue by eporter23** [emory-libraries/dlp-selfdeposit#184]
As we deposit test works into the application, we can see the Universal Viewer load and a manifest is generated, but no images are displayed.
Since we will have only a small number of works with image-based content, we should investigate if we can use the basic RIIIF server option provided by Hyrax, or if we running into any bugs related to Hyrax 5 with Fedora 6.

Note: early on, I enabled the Hyrax feature for caching manifests in the UI, so we can turn that off if it helps with troubleshooting.  

Example works in arch (which appear to have manifests, but do not load images): 
https://oe24-arch.libraries.emory.edu/concern/publications/e6bb79ea-edd5-4f0b-9f80-f03731a469fb?locale=en
https://oe24-arch.libraries.emory.edu/concern/publications/2075a5ff-2abe-4d32-80e5-2c5821920bc2?locale=en

**Comment by bwatson78** [comment]
Initial findings: The first linked example isn't delivering because the object is older than an override we made to ensure that created fileset objects use the `::FileSet` class instead of the root class of `Hyrax::FileSet`. We should preferably wipe the databases soon because there's a mix of objects that will produce a range of behaviors based on our setting evolution.

As far as newer objects that we expect to be shown via RIIIF, I have confirmed that that gem is working correctly. My local machine is delivering images via the UV after I `yarn install`ed. I have found that a certain Rails setting may help up retrieve the images as expected, because I'm receiving the following error when RIIIF attempts to pull the images:
<img width="811" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBeEtmQkE9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--4d59ad09b388b043f085a6e81ec61f40cd4f8870/image.png" alt="image.png" />

This page recommends that a new Rails ENV be set when local environments are fine but production deployed sites fail.

**Comment by bwatson78** [comment]
I spoke with Daniel Pierce about the issue and error codes I've been seeing. He mentioned that the the No Routes match errors that show up occasionally may point to the server not delivering files we know are there, much like the banner issues we've been having. Walking through the FileResolver from the rails console, I can confirm that we have had temporary copies successfully persist to `/tmp`, like `/tmp/fedora___10.65.89.199_8080_fcrepo_rest_production_a3b0c368-cb2f-4624-a9b0-c9496f5552e4_original`, but the application fails to retrieve them like our development instance can. It feels like this is related to the banner issue, but the error message above doesn't confirm that.

The id shown in the screenshot is formatted exactly the way it is in development but production errs while development doesn't. I need a different set of eyes on this. I'm going to write a bug ticket concerning this issue and ask that @alexBLR or @abelemlih pick it up to get fresh eyes on it.

**Comment by bwatson78** [comment]
Bug ticket created: https://app.zenhub.com/workspaces/dlp-self-deposit-65a7f6937b42b04b7bc5d018/issues/gh/emory-libraries/dlp-selfdeposit/250

**Comment by eporter23** [comment]
RIIIF creates an on the fly cache in /tmp when it pulls an image and then also has a dead-by date.  We should also test turning off the manifest caching to see if we still see the same errors.

**Comment by eporter23** [comment]
If caching is working as expected we hope that the use of /tmp on the server would not get overloaded but we can keep an eye on this for /tmp cleanup processes.
