### ISSUE TITLE
Configure Branding Symlink

### ISSUE THREAD

**Issue by rotated8** [emory-libraries/dlp-selfdeposit#284]
The branding folder needs to be symlinked to the same location as `$HYRAX_BRANDING_PATH` for images to show up properly in AWS envs.

Curate does this with Capistrano in [deploy.rb](https://github.com/emory-libraries/dlp-curate/blob/main/config/deploy.rb#L104-L116) and [production.rb](https://github.com/emory-libraries/dlp-curate/blob/main/config/deploy/production.rb#L5).

Currently, we have a `.keep` file in the branding folder to ensure it exists for Docker.

- [x] Develop a solution that works for both Docker and AWS

**Comment by bwatson78** [comment]
PR made: https://github.com/emory-libraries/dlp-selfdeposit/pull/306

**Comment by eporter23** [comment]
To do: Emily will share steps to test this locally and in deployed environments

**Comment by eporter23** [comment]
If you need to test this locally, [follow the steps in this document](https://docs.google.com/document/d/1a_Jp0PPm9OnQTAZRI-I9z1mPv8kw7LLMRsqJKWSwFWE/edit#heading=h.gwz039b925aa) related to setting up a Collection Type, and then creating an instance of the Collection Type. Note that the Collection Type settings are significant because you have to ensure the Collections can support Branding (banner images etc).
