### ISSUE TITLE
Investigate PDF viewer options

### ISSUE THREAD

**Issue by eporter23** [emory-libraries/dlp-selfdeposit#400]
The majority of content we will migrate into OpenEmory consists of PDFs. Because Hyrax does not provide any direct in-browser viewing functionality for PDF files, this means that end users can only see a thumbnail of a PDF and they must then download it in order to preview its contents. This feature has also been requested as an enhancement for Curate and Lux by stakeholders, so work that we can do research this will help multiple products.

Ideally, we could configure additional viewing options for PDFs. One example of this on a Hyrax instance is here:
https://ldr.lafayette.edu/concern/publications/9019s417m

For this ticket, we should:

- Research Samvera implementations of in-browser PDF viewing
- Discuss options to allow switching between the standard Universal Viewer/IIIF displays vs. PDF viewing depending on the type of FileSet selected as the "representative media" in the Hyrax edit form
- Determine the level of effort to implement 

Additional Notes:

SoftServ has done work to support PDF.js in Hyku: https://github.com/scientist-softserv/palni-palci/issues/125

Universal Viewer [may also support use of PDF.js](https://github.com/UniversalViewer/universalviewer/blob/d78d47d0/src/content-handlers/iiif/extensions/uv-pdf-extension/config/Config.ts#L16): 

From a UV community Slack discussion, the following was noted: 

> UV has two different PDF integrations -- the default one uses PDF.js, but there's a setting that can switch to PDFObject, which uses browser-native PDF support instead of a full library. I encountered problems with PDF.js, so I've been using PDFObject since the beginning; I believe that may offer text copying support if PDF.js does not (though its main downside is that the UV experience is less consistent from browser to browser).

**Comment by eporter23** [comment]
Level of effort to implement: 5-8

**Comment by abelemlih** [comment]
@eporter23 The following are my findings:

- I recommend we use [pdf.js](https://mozilla.github.io/pdf.js/) for the pdf viewer, since it is a reliable library used by other Samvera partners who also use Hyrax
- As far as switching between the standard Universal Viewer/IIIF displays vs. PDF viewing, this is a simple override we can add to the show page view to adjust viewer based on the representative fileset type
- Level of effort to implement: 5-8. I have a working demo of a pdf.js viewer with a pdf fileset using our current application (as demoed on our mid-sprint call), but some things I predict will take additional time: 1. Looking into installing pdf.js using Yarn instead of adding the entire library directly to the public folder. If that proves to be unfeasible, I will just add it to the public folder similar to implementations by other institutions. 2. Customizing the actual pdf.js viewer, and ensuring it only contains functionality we want users to have. 3. Any other show view customizations we want to add based on the type of representative file set.

Let me know if there are any additional items to research. Otherwise, we can create the implementation ticket and close this ticket.

**Comment by eporter23** [comment]
Thanks for the demo yesterday @abelemlih - excited to see this move forward!
