### ISSUE TITLE
Investigate on-demand Fixity Checks for FileSets

### ISSUE THREAD

**Issue by eporter23** [emory-libraries/dlp-selfdeposit#434]
For this ticket, we want to investigate the potential to recreate the Fixity Check option offered in the View FileSet UI.
This was previously supported in Hyrax with Fedora 4 and we enabled it for Curate.
It is also possible to navigate to the Fedora 6 UI and run a fixity check on demand. 

Desired features:

- A user can navigate to the View FileSet page and click a Fixity Check button in order to check the file attached
- A user receives a status response for the fixity check
- The results are stored as a Preservation Event

Possible references:
https://wiki.lyrasis.org/display/FEDORA6x/RESTful+HTTP+API+-+Fixity

Ticket outcomes:

- [x] Research and document options in this ticket
- [x] Estimate level of effort to implement for Emory
- [x] Estimate level of effort to share back to Hyrax/Fedora 6 users

**Comment by bwatson78** [comment]
It is possible to use the current Hyrax structure to implement Fixity Checking with the Fedora v6.5 API. We would need to rewrite `app/jobs/fixity_check_job.rb` to work with Valkyrie instead of the current ActiveFedora interface. This is beneficial for the fact that the Job has the structure used to persist logs (`ChecksumAuditLog`) which is still in place and is agnostic as far as what information it takes in to document the FixityChecks.
We would then use the current default Fixity Service ('https://github.com/samvera/active_fedora/blob/main/lib/active_fedora/fixity_service.rb`) only as a template as to what class methods we need to use with `FixityCheckJob`. 

Preliminary list: initialize, expected_message_digest, and check.

Practically everything else can be rewritten to suit our needs as far as communicating with the Fedora API.

**Comment by bwatson78** [comment]
**Estimate level of effort to implement for Emory**:
The rewriting of `app/jobs/fixity_check_job.rb` to make it purely compatible with our Valkyrie application would be an estimate of a 5. The main challenges are to identify what processes tied to the Job are absolutely necessary for our needs (like do we need to keep the `FixityCheckFailureService`, which is largely used for reporting, or use `PreservationEvents` instead.)

For the new Valkyrie service, I'd estimate at least an 8. This is because we'd want to match the output of the ActiveFedora objects as much as we can, which takes time.

**Estimate level of effort to share back to Hyrax/Fedora 6 users**: We'd definitely would take each estimate above and raise them up to their next level higher. In order to be compliant with Hyrax, we'd have to ensure backwards compatability and write tests that would work for either ActiveFedora or Valkyrie, which takes time.

**Comment by eporter23** [comment]
Thanks @bwatson78 ! I'll write up a ticket for the backlog to implement for Emory (if we have time).
