### ISSUE TITLE
Investigate options for alternate_id usage

### ISSUE THREAD

**Issue by eporter23** [emory-libraries/dlp-selfdeposit#541]
When we implemented our locally defined NOID scheme, we learned that the Valkyrie implementation of doing this results in an additional, separate Fedora object getting created for Collections, Works and Filesets. This will heavily increase our Fedora object count, which could be a concern for performance.

To investigate:
Could we define our own distinct attribute to store the locally minted NOID (and bypass `alternate_id`)?
Can we determine why Valkyrie doesn't set our locally minted NOID as the actual ID, instead requiring the UUID?
Can we determine why we can't just store the string value of the locally defined ID in Valkyrie?
If we make changes, what additional work is needed to support our local IDs and persistent URLs?

**Comment by eporter23** [comment]
Discussed in standup today that we would also like to capture technical details about why the recommended approach isn't working, so we can write up a ticket for the Samvera community for other adopters. @alexBLR will also increase the estimate as needed.

**Comment by alexBLR** [comment]
### Could we define our own distinct attribute to store the locally minted NOID (and bypass alternate_id)?

Yes. To avoid creating additional Fedora objects while maintaining our NOID functionality, we can create a new internal string attribute emory_noid, modify our transition step with that attribute, update indexer to that attribute, remove all related alternate_ids queries, and modify display functionality.

### Can we determine why Valkyrie doesn't set our locally minted NOID as the actual ID, instead requiring the UUID?
The requirement for UUIDs as primary IDs in Valkyrie is by design. 
Here's why: https://github.com/samvera/valkyrie/blob/main/lib/valkyrie/id.rb#L6-L11
All Valkyrie persisters
1. Generate UUIDs for new resources
2. Never allow setting of IDs manually
3. Return persisted resources with their permanent ID set


### Self-Deposit The current implementation

We Generate a NOID using Noid::Rails::Service.new.mint and append "-emory" to the NOID
We store it in the alternate_ids attribute in fedora by setting it in one of the transaction steps set_noid_id.rb
We define alternate_ids in our emory_internal_metadata.yaml
We also Index it in Solr as alternate_ids_ssim for Publications in publcation_indexer.rb
We display it in _purl.html.erb


### Why current implementation it doesn’t work

In Valkyrie, `alternate_ids` is implemented as a relationship between objects rather than a simple attribute. 

When you set an `alternate_id`, Valkyrie:
1. Creates a new RDF resource in Fedora to represent that ID
2. Establishes a relationship between your main object (Work/Collection/FileSet) and this new ID resource
3. Each ID becomes its own distinct object in Fedora with its own URI

So for each object in your repository:
- If it's a Work, you get 2 Fedora objects (the Work + its NOID object)
- If it's a Collection, you get 2 Fedora objects (the Collection + its NOID object)
- If it's a FileSet, you get 2 Fedora objects (the FileSet + its NOID object)

If we store a simple string attribute, which would just be a property on the main object, it wouldn't create additional Valkyrie resources.


### Technical Explanation
The alternate identifier functionality is implemented as Valkyrie Resources.

https://github.com/samvera/valkyrie/blob/main/lib/valkyrie/persistence/fedora/persister/alternate_identifier.rb

**How Alternate IDs are Stored**
Each alternate ID becomes its own Valkyrie::Resource

These resources have a "references" attribute that points back to the main resource

This creates a bidirectional relationship between the main resource and its alternate identifiers.

**Query Support**

The system supports finding resources by their alternate identifiers through: https://github.com/samvera/valkyrie/blob/main/lib/valkyrie/persistence/memory/query_service.rb#L38

**Persistence Behavior**
When saving resources with alternate IDs:
New alternate identifier resources are created
Existing ones are updated
Removed ones are deleted

You can find it here: https://github.com/samvera/valkyrie/blob/main/lib/valkyrie/persistence/fedora/persister.rb#L25
https://github.com/samvera/valkyrie/blob/main/lib/valkyrie/persistence/fedora/persister.rb#L94-L103

**Comment by eporter23** [comment]
This is great, @alexBLR - thank you. I'll work on writing up a new ticket for implementing our workaround, but what you have provided here will be really helpful for sharing with the Hyrax-Fedora 6 user community.

**Comment by eporter23** [comment]
I've written up #607 as a followup ticket for implementation.
