### ISSUE TITLE
ORCID ID Validation URL Strip

### ISSUE THREAD

**Issue by eporter23** [emory-libraries/dlp-selfdeposit#609]
Strip the URL of the https://orcid.org/0000-0003-0405-6178 so it would only leave 0000-0003-0405-6178

**Comment by maxdmayhew** [comment]
<img width="556" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBOGpVQnc9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--db0645600eca03156be004ee9b220ffb0f899347/Screenshot%202024-11-20%20at%201.16.17%E2%80%AFPM.png" alt="Screenshot 2024-11-20 at 1.16.17 PM.png" />

@eporter23 does this work for the error message?

Updating because of my original URL regex isnt working as well as I thought it it would.

**Comment by eporter23** [comment]
@maxdmayhew error message looks great, and I also am not sure about whether those anchor tags should exist or not, but they do give good contrast between the different types of entries. I went to the ORCID site to see if they have any resolvable examples, and they do! So maybe this would be good to use, because it does not that it's not a real person in case someone clicks on it. https://orcid.org/0000-0002-2771-9344

**Comment by maxdmayhew** [comment]
https://github.com/emory-libraries/dlp-selfdeposit/commit/ececc8b7547ae040958c438da08458d73ff0e2b1#diff-9137d1db24fe98a1cab96c43096b8e694ba2060ffa09cd52aeba298d47ce3a43R329

I somehow messed up the error message. Need to fix.

**Comment by eporter23** [comment]
Looks good @maxdmayhew ! If any refinements are needed I'll write up a new ticket.
