### ISSUE TITLE
Review Submissions UI is no longer listing work details

### ISSUE THREAD

**Issue by eporter23** [emory-libraries/dlp-selfdeposit#623]
**Describe the bug**
The Review Submissions UI is no longer showing individual works, only a count of works still under review. See oe24-test environment which has a number of works still under review.

**To Reproduce**
1. Login as Admin
2. Navigate to the Dashboard > Tasks > Review Submissions section
3. Look at the Under Review tab 
4. See a count of works still under review (in oe24-test, there are 96) and pagination for the results
5. Note that none of the works are actually listed or accessible 

**Expected behavior**

The Under Review tab should show details about each work, including a link to the work, depositor, date, etc. 

**Screenshots**

<img width="1666" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBekdvQnc9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--9fa6ffc946797b86e627e9327ca1133cb98f3d20/Screenshot%202024-11-08%20at%2010.40.50%E2%80%AFAM.png" alt="Screenshot 2024-11-08 at 10.40.50 AM.png" />

**Desktop (please complete the following information):**
 - OS: Mac OS
 - Browser: Chrome
 - Version: latest

**Comment by bwatson78** [comment]
Preliminary Findings: I can get 56 out of 95 claimed works to display by selecting `Show 100 per page`. When 10 is chosen and clicking pages 1 through 3, nothing still shows and page 4 displays only one object. My guess is that something is wrong with the pulling of objects in the controller. This may be a case of empty objects pulled into an array.

**Comment by bwatson78** [comment]
I can confirm that this is a Hyrax bug, since we haven't altered any of the code feeding the documents to this page. Now assessing the cause of the issue and estimating the fix.

**Comment by bwatson78** [comment]
Let me reverse my initial findings: There are `Sipity:Workflow` objects (Postgres) still present that are tied to now long gone objects we've since manually deleted. With a brand new environment with no lingering test objects present, this page should act as expected. The behavior we're seeing now is that the index is pulling all `Sipity::Workflow` objects of an indicated state (deposited or not) at the per page amount. The object will only show on the page if there's an associated Solr object present. If none, blank page. This is why it's best to delete objects through the UI--all steps get called to remove associated objects.
