### ISSUE TITLE
Setup AWS monitoring - oe24-test

### ISSUE THREAD

**Issue by eporter23** [emory-libraries/dlp-selfdeposit#659]
This ticket follows the work done for oe24-arch:

Monitoring for the application should track CPU and Memory usage.

This ticket is complete when Cloudwatch has data for:

- [x]  CPU usage
- [x]  Memory Usage

**Comment by kbowaterskelly** [comment]
It looks like whatever script is probably normally run to install and configure the cloudwatch agent has not been run in this case. Rather than build something from scratch, I'd like to ask @jcrompton42 to please run the script, if it exists, and provide a little information about that process, so as not to duplicate work.

**Comment by jcrompton42** [comment]
dashboard created here
https://us-east-1.console.aws.amazon.com/cloudwatch/home?region=us-east-1#dashboards/dashboard/hyrax-test
