### ISSUE TITLE
oe24-arch: NoMethodError on homepage

### ISSUE THREAD

**Issue by eporter23** [emory-libraries/dlp-selfdeposit#661]
**Describe the bug**
While testing in oe24-arch on 11/25, I logged in as the Admin user but while navigating through the site, I received an error when trying to get back to the homepage.

**To Reproduce**
1. Start a new (non-incognito) browser session
2. Go to the oe24-arch homepage
3. Login as the admin user
4. Navigate throughout the site, including the Dashboard
5. Click the "Home" link in the upper left navigation
6. See `NoMethodError in Hyrax::Homepage#index`
7. Try again to reach the homepage using the base URL https://https://oe24-arch.libraries.emory.edu/ 
8. See the same error
9. 

NOTE: If I start a new session in incognito mode, the error does not occur. 

**Expected behavior**

If a user is logged in, they should be able to navigate to the homepage without errors

**Screenshots**

**Desktop (please complete the following information):**

**Smartphone (please complete the following information):**

**Additional context**

**Comment by bwatson78** [comment]
This is caused by the `User#user_key_field` changing in the Shibboleth branch deployed to Arch to `:uid`. The test users do not have this attribute assigned, which would fix the issue. Since @alexBLR is currently working with this branch, I will defer to him to make the changes necessary for this bug.
