### ISSUE TITLE
Spike: assess level of effort to implement Curate Preservation Events for OpenEmory

### ISSUE THREAD

**Issue by eporter23** [emory-libraries/dlp-selfdeposit#87]
For this ticket, we want to assess level of effort for how to bring over our Preservation Events implemented in Curate to OpenEmory/Hyrax 5.

Work will include:

- [x] Look at the codebases
- [x] Write up findings about level of effort in comments on this ticket

**Comment by bwatson78** [comment]
We can follow the same model structure of `PreservationEvent`  and `PreservationWorkflow`. Instead of treating them as true nested attributes, we should tie the events and workflows to the parent (`FileSet` or `Publication`) with an attribute in each new model of `parent_id`. Doing so will allow us to draft a new Custom Query (Valkyrie's preferred lookup system) that finds all objects with `internal_resource` of, say, `PreservationEvent with a field of `parent_id` that equals the Publication in question. Ordering can happen within the same query, sorting by `created_at`.

The true difference in the way we construct the models is that they will be simpler objects. I recommend we model them after [Hyrax' Embargo](https://github.com/samvera/hyrax/blob/main/app/models/hyrax/embargo.rb). This resembles the models we were building in our Valkyrie prototype. For indexing, we could use our Custom Queries to pull Events and/or Workflows much in the same way we do now with Curate.

Looking at [how Embargoes are associated to objects](https://github.com/samvera/hyrax/blob/c571eda1626dfe99e307d198d23364654934efae/app/models/hyrax/resource.rb#L168), we could follow that convention instead. Following this method, we could add attributes to both `Publication` and `FileSet` of `pres_event_ids` and/or `pres_worflow_ids`. Instead of `preservation_event=`, we could make a method called `add_preseveration_event` that would add the new `PreservationEvent`'s id to an object's attribute of `pres_event_ids`, which would be an array we convert to a string when stored to preserve order (or a comma-separated list--your choice).

The workflow for an action ticket would be the following (the first three tasks have an estimate of 5):

- [ ] Create the models in the same fashion of Embargo, matching the attributes to the same classes in Curate.
- [ ] Stub the same attributes into `Publication` and `FileSet`'s indexers. (FileSet's indexer would have to be brought in or prepended in an initializer.)
- [ ] Either make the parent object aware of it's own Preservation classes or make these new classes aware of their parent. I'd recommend the "parent object aware" way since it follows programmatic conventions we're already accustomed to.
- [ ] Finally, I'd recommend two other tickets that 1. inject the creation of Preservation classes into desired operations (estimate of 5) and 2. display the created Preservation class attributes in show pages (another estimate of 5).

**Comment by eporter23** [comment]
Thanks @bwatson78 ! Do you have any sense of what this may look like in Fedora itself, as in, if you look at a given Work or FileSet object in Fedora (not via Hyrax), what would the event relationship look like? I realize we can also test this out once implemented.

**Comment by bwatson78** [comment]
PreservationEvent objects would be just like how ACLs are currently--separate objects tied by a field containing an id associating it to its parent.

**Comment by eporter23** [comment]
Thanks @bwatson78 - I think it will be helpful to "see" what these look like, so maybe we can build out one event as a first step.

**Comment by abelemlih** [comment]
@eporter23 the implementation path above makes sense to me. This ticket is ready to close.

**Comment by eporter23** [comment]
Zo will review this and we will close before the end of the sprint.
